### ISSUE TITLE
It's not working on android but working on desktop .

### ISSUE THREAD

**Issue by gauravnagar192** [bradtraversy/mern_shopping_list#6]
when i searched this issue on stackoverflow it may be bcoz redux dev tool extension in not in mobile browsers so how to make it work in mobile browsers

**Comment by afsaa** [comment]
I also had the same problem but I found how to fix it. Here a leave you the link. Hope it helps :D.
https://stackoverflow.com/questions/41333376/reactjs-app-doesnt-work-on-mobile

**Comment by sphred5** [comment]
Thanks @afsaa that fix worked!

**Comment by leslie-alldridge** [comment]
@gauravnagar192 have you removed dev tools extension as afsaa recommended? Doing so should fix it and the issue can be closed.

**Comment by gauravnagar192** [comment]
@leslie-alldridge Main problem is this app require dev tool to work but other devices (mobile) dont have dev tool installed so how to make it work in them without dev tool ?

**Comment by leslie-alldridge** [comment]
the app only needs dev tools when you're coding along. once it's deployed / you've finished working on it, remove the dev tools so it works on mobile

**Comment by gauravnagar192** [comment]
@leslie-alldridge After deploying app . app still not working without dev tool .  bcoz it taking something from dev tool to initialize . you can see gauravtask.herokuapp.com here that exact same app not working without dev tool .

**Comment by dulerong** [comment]
For me simply commenting out or deleting the following worked.
window._REDUX_DEVTOOLS_EXTENSION_ && window.__REDUX_DEVTOOLS_EXTENSION__()

**Comment by bradtraversy** [comment]
Thanks, @gauravnagar192! The fix is in the comments — the linked StackOverflow answer resolved it for other users too. The proper `composeEnhancers` pattern from issue #20 also removes the hard dependency on the DevTools extension. Closing as resolved.
